name: "Pytest DevInfra Metrics"
description:
  "Collect test data and upload it to our internal test data collection service."

inputs:
  path:
    description:
      "Path to test data output artifact to upload to our internal test data
      collection service"
    required: true
    default: .artifacts/pytest-report.json

  _gcp_project:
    description: "for testing, only"
    required: true
  _deploy_environ:
    description: "for testing, only: `prod` or `dev`"
    required: true

  __shell:
    description: "private -- do not use"
    required: true
    default: bash -euxo pipefail {0}

runs:
  using: "composite"
  steps:
    - name: Collect DevInfra Metrics
      uses: ./_send-to-devinfra-metrics
      with:
        path: ${{ inputs.path }}
        upload-type: pytest
        _gcp_project: ${{ inputs._gcp_project }}
        _deploy_environ: ${{ inputs._deploy_environ }}
