name: Self-Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Use Action
        id: test-action
        uses: ./
        with:
          path: .artifacts/junit.xml
          gcs_path: ${{ secrets.GCS_BUCKET }}
          gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.SENTRY_GCP_DEV_WORKLOAD_IDENTITY_POOL }}
          service_account: ${{ secrets.SUDO_GCP_SERVICE_ACCOUNT }}
